import type { NextPage } from 'next';
import Head from 'next/head';
import Card from '../components/common/card.common';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div>
				<div>Home</div>
				<Card title='Pustaka Jasa' stack='React, React Native, Express, MongoDB, Stripe' body="An eCommerce app that allows parents to purchase their children's needs from the comfort of their home." href={'https://google.com'} />
			</div>
		</>
	);
};

export default Home;
